apiVersion: v1
kind: Service
metadata:
  name: {{ include "paradedb.fullname" . }}
  labels:
    {{- include "paradedb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "paradedb.selectorLabels" . | nindent 4 }}
