{{- if and .Values.persistence.storage.enabled (not .Values.persistence.storage.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "affine.fullname" . }}-storage
  labels:
    {{- include "affine.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.storage.size }}
  {{- if .Values.persistence.storage.storageClass }}
  storageClassName: {{ .Values.persistence.storage.storageClass | quote }}
  {{- end }}
---
{{- end }}
{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "affine.fullname" . }}-config
  labels:
    {{- include "affine.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.config.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
  {{- if .Values.persistence.config.storageClass }}
  storageClassName: {{ .Values.persistence.config.storageClass | quote }}
  {{- end }}
{{- end }}
