{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "affine.fullname" . }}
  labels:
    {{- include "affine.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and (not .Values.paradedb.enabled) .Values.database.url }}
  DATABASE_URL: {{ .Values.database.url | quote }}
  {{- end }}
  {{- if and (not .Values.paradedb.enabled) (not .Values.database.url) .Values.database.username }}
  DB_USERNAME: {{ .Values.database.username | quote }}
  {{- end }}
  {{- if and (not .Values.paradedb.enabled) (not .Values.database.url) .Values.database.password }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  {{- end }}
  {{- if and (not .Values.redis.enabled) .Values.externalRedis.password }}
  REDIS_SERVER_PASSWORD: {{ .Values.externalRedis.password | quote }}
  {{- end }}
  {{- if not .Values.extraSecrets }}
  {}
  {{- end }}
  {{- range $key, $val := .Values.extraSecrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
