{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}