apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tailscale-subnet-router.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "tailscale-subnet-router.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tailscale-subnet-router.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "tailscale-subnet-router.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "tailscale-subnet-router.serviceAccountName" . }}
      containers:
        - name: {{ include "tailscale-subnet-router.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: {{ .Values.securityContext.privileged }}
          env:
            - name: TS_KUBE_SECRET
              value: "tailscale"
            - name: TS_USERSPACE
              value: "false"
            - name: TS_DEBUG_FIREWALL_MODE
              value: "auto"
            {{- with .Values.additionalEnvs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}