{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tailscale-subnet-router.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "tailscale-subnet-router.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}