replicaCount: 1

image:
  repository: vaultwarden/server
  tag: latest
  pullPolicy: IfNotPresent

mariadb:
  enabled: true
  image:
    repository: mariadb
    tag: latest
    pullPolicy: IfNotPresent
  databaseSecret: vaultwarden-db-secret

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: vaultwarden.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "250m"

nodeSelector: {}
tolerations: []
affinity: {}