apiVersion: v2
name: maybefinance
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "1.16.0"
home: https://github.com/maybe-finance/maybe
sources:
  - https://github.com/maybe-finance/maybe
maintainers:
  - name: Simon Franken
    email: mail@simon-franken.de
keywords:
  - finance
  - self-hosted
  - rails
kubeVersion: ">=1.24.0-0"

dependencies:
  - name: postgresql
    version: 16.4.5
    repository: "oci://registry-1.docker.io/bitnamicharts"
