apiVersion: v1
kind: Service
metadata:
  name: {{ include "headscale.fullname" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
      targetPort: 8080
    - port: {{ .Values.service.metricsPort }}
      protocol: TCP
      name: metrics
      targetPort: 9090
  selector:
    {{- include "headscale.selectorLabels" . | nindent 4 }}