apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "searxng.fullname" . }}
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
data:
  settings.yml: |
    {{- if .Values.settings.customSettings }}
    {{- .Values.settings.customSettings | nindent 4 }}
    {{- else }}
    use_default_settings: true
    general:
      instance_name: {{ .Values.settings.instanceName | quote }}
      enable_metrics: true
    search:
      safe_search: {{ .Values.settings.safeSearch }}
      autocomplete: {{ .Values.settings.autocomplete | quote }}
      default_lang: {{ .Values.settings.defaultLang | quote }}
      formats:
        {{- range .Values.settings.formats }}
        - {{ . }}
        {{- end }}
    server:
      port: 8080
      bind_address: "0.0.0.0"
      limiter: {{ .Values.settings.limiter }}
      public_instance: {{ .Values.settings.publicInstance }}
      image_proxy: {{ .Values.settings.imageProxy }}
    {{- end }}
