{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "searxng.fullname" . }}
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
type: Opaque
stringData:
  secretKey: {{ .Values.secret.secretKey | default (randAlphaNum 32) | quote }}
{{- end }}
