apiVersion: v2
name: basic
description: A basic Helm chart for Kubernetes
type: application
version: 0.3.1
appVersion: "1.16.0"
home: https://github.com/simonfranken/Charts
sources:
  - https://github.com/simonfranken/Charts
maintainers:
  - name: Simon Franken
    email: mail@simon-franken.de
keywords:
  - starter
  - application
  - kubernetes
kubeVersion: ">=1.24.0-0"
