image:
  repository: ghcr.io/juanfont/headscale
  tag: "v0.26"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 8080
  metricsPort: 9090

persistence:
  enabled: true # enable/disable PVC for /lib and /run
  accessModes: ["ReadWriteOnce"]
  storageClass: "" # if empty, use cluster default
  sizeLib: 1Gi
  sizeRun: 512Mi

ingress:
  enabled: true
  className: "" # ingressClassName (""=use cluster default)
  annotations: {}
  hosts:
    - host: "headscale.example.com"
      paths:
        - path: /
          pathType: Prefix
  tls: # leave empty if no TLS is needed
    - secretName: headscale-tls
      hosts:
        - headscale.example.com

config:
  server_url: http://127.0.0.1:8080
  listen_addr: 0.0.0.0:8080
  metrics_listen_addr: 0.0.0.0:9090
  grpc_listen_addr: 0.0.0.0:50443
  grpc_allow_insecure: false

  noise:
    private_key_path: /var/lib/headscale/noise_private.key

  prefixes:
    v4: 100.64.0.0/10
    v6: fd7a:115c:a1e0::/48
    allocation: sequential

  derp:
    urls:
      - https://controlplane.tailscale.com/derpmap/default
    auto_update_enabled: true
    update_frequency: 24h

  ephemeral_node_inactivity_timeout: 30m

  database:
    type: sqlite
    sqlite:
      path: /var/lib/headscale/db.sqlite
      write_ahead_log: true
      wal_autocheckpoint: 1000

  log:
    format: text
    level: info

  policy:
    mode: file
    path: ""

  dns:
    magic_dns: true
    base_domain: example.com
    override_local_dns: false
    nameservers:
      global:
        - 1.1.1.1
        - 1.0.0.1
        - 2606:4700:4700::1111
        - 2606:4700:4700::1001
      split: {}
    search_domains: []
    extra_records: []

  unix_socket: /var/run/headscale/headscale.sock
  unix_socket_permission: "0770"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
