apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustfs.fullname" . }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.consolePort }}
      targetPort: console
      protocol: TCP
      name: console
  selector:
    {{- include "rustfs.selectorLabels" . | nindent 4 }}
