{{- $secret := lookup "v1" "Secret" .Release.Namespace (include "vaultwarden.secret.name" .) -}}
{{- if not $secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.secret.name" . }}
  labels:
    {{ include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  MYSQL_DATABASE: {{ .Values.mariadb.database | b64enc }}
  MYSQL_USER: {{ .Values.mariadb.username | b64enc }}
  MYSQL_PASSWORD: {{ if eq .Values.mariadb.password "auto" }}{{ randAlphaNum 16 | b64enc }}{{ else }}{{ .Values.mariadb.password | b64enc }}{{ end }}
{{- end -}}