{{- $secret := lookup "v1" "Secret" .Release.Namespace (include "vaultwarden.secret.name" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.secret.name" . }}
  labels:
    {{ include "vaultwarden.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: pre-install
type: Opaque
data:
  {{- if $secret }}
  MYSQL_ROOT_PASSWORD: {{ $secret.data.MYSQL_ROOT_PASSWORD }}
  MYSQL_PASSWORD: {{ $secret.data.MYSQL_PASSWORD }}
  {{- else }}
  MYSQL_ROOT_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  MYSQL_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  {{- end }}
  MYSQL_DATABASE: {{ "vaultwarden" | b64enc }}
  MYSQL_USER: {{ "vaultwarden" | b64enc }}