apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.secret.name" . }}
  labels:
    {{ include "vaultwarden.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,
    "helm.sh/resource-policy": keep
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  MYSQL_DATABASE: {{ "vaultwarden" | b64enc }}
  MYSQL_USER: {{ "vaultwarden" | b64enc }}
  MYSQL_PASSWORD: {{ randAlphaNum 16 | b64enc }}