apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vaultwarden.mariadb.fullname" . }}
  labels:
    {{ include "vaultwarden.mariadb.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "vaultwarden.mariadb.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{ include "vaultwarden.mariadb.labels" . | nindent 8 }}
    spec:
      containers:
        - name: mariadb
          image: {{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "vaultwarden.secret.name" . }}
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "vaultwarden.secret.name" . }}
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "vaultwarden.secret.name" . }}
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "vaultwarden.secret.name" . }}
                  key: MYSQL_PASSWORD
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
            periodSeconds: 5