apiVersion: v2
name: letsencrypt-issuer
description: Creates a letsencrypt certificate issuer for cert-manager to secure your web traffic.
type: application
version: 1.0.1
appVersion: "1.0.0"
home: https://cert-manager.io/docs/configuration/acme/
sources:
  - https://github.com/cert-manager/cert-manager
maintainers:
  - name: Simon Franken
    email: mail@simon-franken.de
keywords:
  - cert-manager
  - letsencrypt
  - acme
kubeVersion: ">=1.24.0-0"
