apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "outline-wiki.fullname" . }}
spec:
  replicas: {{ .Values.outline.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "outline-wiki.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "outline-wiki.name" . }}
    spec:
      containers:
        - name: outline
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
            - name: REDIS_URL
              value: "redis://{{ .Release.Name }}-redis-master:6379"
            {{- if .Values.outline.env }}
            {{- range $key, $value := .Values.outline.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /var/lib/outline/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "outline-wiki.fullname" . }}-data