apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "excalidash.fullname" . }}-backend
  labels:
    {{- include "excalidash.labels" . | nindent 4 }}
data:
  {{- if not (or .Values.backend.env .Values.backend.extraEnv) }}
  {}
  {{- end }}
  {{- range $key, $val := .Values.backend.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- range $key, $val := .Values.backend.extraEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "excalidash.fullname" . }}-frontend
  labels:
    {{- include "excalidash.labels" . | nindent 4 }}
data:
  {{- if not (or .Values.frontend.env .Values.frontend.extraEnv) }}
  {}
  {{- end }}
  {{- range $key, $val := .Values.frontend.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- range $key, $val := .Values.frontend.extraEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
