{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "excalidash.fullname" . }}
  labels:
    {{- include "excalidash.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.secrets.secretEnv }}
  {}
  {{- end }}
  {{- range $key, $val := .Values.secrets.secretEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
