apiVersion: v2
name: redis
description: A lightweight Redis cache Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "7.4"
keywords:
  - redis
  - cache
  - session
  - key-value
home: https://redis.io
sources:
  - https://github.com/redis/redis
maintainers:
  - name: Simon Franken
    email: mail@simon-franken.de
