name: Package Helm Chart

on:
  push:
    branches:
      - main  # Adjust this branch to match your main branch

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.3  # Ensure you use a stable version

      - name: Package Helm Chart
        run: helm package ./basic

      - name: Upload Helm Chart as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: basic
          path: *.tgz